name: "CI"

on:
  push:

permissions:
  contents: read

jobs:
  ci:
    name: "CI"
    runs-on: macos-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Dotfiles
        run: sh ./global-setup.sh
